# This image installs all dependencies and pre-builds an Argus Frontend
# version, in the hopes that a rebuild for production will be faster.
FROM node:16-bullseye
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends tini git


ARG GITREF=master
ARG REPO=https://github.com/Uninett/argus-frontend.git
RUN git clone -b ${GITREF} ${REPO} /app

RUN npm ci
RUN npx browserslist@latest --update-db

RUN npm run build

ONBUILD RUN npm run build

# When used as an intermediate builder image, the complete set of statically
# built files to serve from the web server root can be copied from /app/build
