services:
  api:
    image: ghcr.io/uninett/argus:2.2.1

    ports:
      - "${ARGUS_BACKEND_PORT}:8000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TIME_ZONE=${TIME_ZONE}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - ARGUS_FRONTEND_URL=${ARGUS_FRONTEND_URL}
      - STATIC_ROOT=static/
      - EMAIL_HOST=${EMAIL_HOST}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

      - ARGUS_DATAPORTEN_KEY=notset
      - ARGUS_DATAPORTEN_SECRET=notset

  postgres:
    image: "postgres:14"
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres:
    driver: local
