name: Create and publish Argus images

on:
  push:
    branches: ['test']

env:
  REGISTRY: ghcr.io
  OWNER: uninett

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend builder Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: frontend
          file: frontend/Dockerfile-build
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/argus-frontend-builder:1.6.1
          build-args: |
            VERSION=1.6.1

      - name: Build and push backend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/argus-api:1.9.0
          build-args: |
            GITREF=v1.9.0
            
